# Server Port
server.port=${PORT:8080}

# Database Configuration (PostgreSQL - Supabase)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.iffnvippxbttyaxembqh.supabase.co:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:g9Bw938Wn5CNoLQB}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Properties
# Use update only in dev. Change to validate in prod.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret Base64 encoded (min 256 bits for HS256)
jwt.secret=mXq2aYjRcNvP3uKzB7WfDs8Hg5xL1T9vQcEuJ4oRtMw=
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.mechconnect=DEBUG
